import { expect, test } from "vitest";
import { stub } from "../stub.js";

test("stub entry string", async () => {
  const cwd = process.cwd();

  expect(
    await stub({
      entry: "src/tests/entry/index.ts",
      cwd,
      noEffects: true,
    }),
  ).toMatchInlineSnapshot(`
    Map {
      "${cwd}/dist/index.mjs" => "// This file was auto-generated by ts-stub
    import { require } from "tsx/cjs/api";
    const { bar, bar2, bar3, Foo, Bar, foo } = require("../src/tests/entry/index.ts", import.meta.url);
    export { bar, bar2, bar3, Foo, Bar, foo as default, foo };",
      "${cwd}/dist/index.d.ts" => "// This file was auto-generated by ts-stub
    export * from "../src/tests/entry/index.ts";
    export { default } from "../src/tests/entry/index.ts";",
    }
  `);
});

test("stub entry object", async () => {
  const cwd = process.cwd();

  expect(
    await stub({
      entry: {
        input: "src/tests/entry/index.ts",
        output: "src/tests/dist",
        format: undefined,
      },
      cwd,
      noEffects: true,
    }),
  ).toMatchInlineSnapshot(`
    Map {
      "${cwd}/src/tests/dist/index.mjs" => "// This file was auto-generated by ts-stub
    import { require } from "tsx/cjs/api";
    const { bar, bar2, bar3, Foo, Bar, foo } = require("../src/tests/entry/index.ts", import.meta.url);
    export { bar, bar2, bar3, Foo, Bar, foo as default, foo };",
      "${cwd}/src/tests/dist/index.d.ts" => "// This file was auto-generated by ts-stub
    export * from "../src/tests/entry/index.ts";
    export { default } from "../src/tests/entry/index.ts";",
    }
  `);
});

test("stub entry default", async () => {
  const cwd = process.cwd() + "/src/tests/entry";

  expect(await stub({ cwd, noEffects: true })).toMatchInlineSnapshot(`
    Map {
      "${cwd}/dist/index.mjs" => "// This file was auto-generated by ts-stub
    import { require } from "tsx/cjs/api";
    const { bar, bar2, bar3, Foo, Bar, foo } = require("../src/index.ts", import.meta.url);
    export { bar, bar2, bar3, Foo, Bar, foo as default, foo };",
      "${cwd}/dist/index.d.ts" => "// This file was auto-generated by ts-stub
    export * from "../src/index.ts";
    export { default } from "../src/index.ts";",
    }
  `);
});

test("stub format and extensions", async () => {
  const cwd = process.cwd();

  expect(
    await stub({
      entry: {
        input: "src/tests/entry/index.ts",
        format: "esm:js",
      },
      cwd,
      noEffects: true,
    }),
  ).toMatchInlineSnapshot(`
    Map {
      "${cwd}/dist/index.js" => "// This file was auto-generated by ts-stub
    import { require } from "tsx/cjs/api";
    const { bar, bar2, bar3, Foo, Bar, foo } = require("../src/tests/entry/index.ts", import.meta.url);
    export { bar, bar2, bar3, Foo, Bar, foo as default, foo };",
      "${cwd}/dist/index.d.ts" => "// This file was auto-generated by ts-stub
    export * from "../src/tests/entry/index.ts";
    export { default } from "../src/tests/entry/index.ts";",
    }
  `);

  expect(
    await stub({
      entry: {
        input: "src/tests/entry/index.ts",
        format: "cjs",
      },
      cwd,
      noEffects: true,
    }),
  ).toMatchInlineSnapshot(`
    Map {
      "${cwd}/dist/index.cjs" => "// This file was auto-generated by ts-stub
    const tsx = require("tsx/cjs/api");
    module.exports = require("../src/tests/entry/index.ts", __dirnmame);",
      "${cwd}/dist/index.d.ts" => "// This file was auto-generated by ts-stub
    export * from "../src/tests/entry/index.ts";
    export { default } from "../src/tests/entry/index.ts";",
    }
  `);

  expect(
    await stub({
      entry: {
        input: "src/tests/entry/index.ts",
        format: "cjs:cjs",
      },
      cwd,
      noEffects: true,
    }),
  ).toMatchInlineSnapshot(`
    Map {
      "${cwd}/dist/index.cjs" => "// This file was auto-generated by ts-stub
    const tsx = require("tsx/cjs/api");
    module.exports = require("../src/tests/entry/index.ts", __dirnmame);",
      "${cwd}/dist/index.d.ts" => "// This file was auto-generated by ts-stub
    export * from "../src/tests/entry/index.ts";
    export { default } from "../src/tests/entry/index.ts";",
    }
  `);
});

test("stub should not emit", async () => {
  const cwd = process.cwd();

  expect(
    await stub({
      entry: {
        input: "src/tests/entry/index.ts",
        noEmit: true,
      },
      cwd,
      noEffects: true,
    }),
  ).toMatchInlineSnapshot(`
    Map {
      "${cwd}/dist/index.mjs" => "// This file was auto-generated by ts-stub
    import { require } from "tsx/cjs/api";
    const { bar, bar2, bar3, Foo, Bar, foo } = require("../src/tests/entry/index.ts", import.meta.url);
    export { bar, bar2, bar3, Foo, Bar, foo as default, foo };",
    }
  `);
});

test("stub multiple entries", async () => {
  const cwd = process.cwd();

  expect(
    await stub({
      entry: [
        { input: "src/tests/entry/index.ts", output: "src/tests/dist" },
        { input: "src/tests/entry/anon.ts", output: "src/tests/dist" },
      ],
      cwd,
      noEffects: true,
    }),
  ).toMatchInlineSnapshot(`
    Map {
      "${cwd}/src/tests/dist/index.mjs" => "// This file was auto-generated by ts-stub
    import { require } from "tsx/cjs/api";
    const { bar, bar2, bar3, Foo, Bar, foo } = require("../src/tests/entry/index.ts", import.meta.url);
    export { bar, bar2, bar3, Foo, Bar, foo as default, foo };",
      "${cwd}/src/tests/dist/index.d.ts" => "// This file was auto-generated by ts-stub
    export * from "../src/tests/entry/index.ts";
    export { default } from "../src/tests/entry/index.ts";",
      "${cwd}/src/tests/dist/anon.mjs" => "// This file was auto-generated by ts-stub
    import { require } from "tsx/cjs/api";
    const { default: _default } = require("../src/tests/entry/anon.ts", import.meta.url);
    export { _default as default };",
      "${cwd}/src/tests/dist/anon.d.ts" => "// This file was auto-generated by ts-stub
    export { default } from "../src/tests/entry/anon.ts";",
    }
  `);
});
